"""Add risk_score and risk_class columns to HealthData

Revision ID: 26c29f191df1
Revises: 7cd647d64f40
Create Date: 2025-06-24 15:34:46.684468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26c29f191df1'
down_revision = '7cd647d64f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_class', sa.String(length=10), nullable=True))
        batch_op.alter_column('blood_pressure',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('risk_class')
        batch_op.drop_column('risk_score')

    # ### end Alembic commands ###
