"""Add is_from_patient to doctor_messages

Revision ID: 77fe75558dd3
Revises: 7ecb42b53067
Create Date: 2025-06-22 16:10:51.427903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe75558dd3'
down_revision = '7ecb42b53067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_patient', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_messages', schema=None) as batch_op:
        batch_op.drop_column('is_from_patient')

    # ### end Alembic commands ###
