"""Add blood_pressure and glucose_level to HealthData

Revision ID: 7cd647d64f40
Revises: c50f70a3fad1
Create Date: 2025-06-24 09:58:05.310139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cd647d64f40'
down_revision = 'c50f70a3fad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
