"""Add health_data relationship

Revision ID: 7ecb42b53067
Revises: b2436af03029
Create Date: 2025-06-14 20:28:45.658454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecb42b53067'
down_revision = 'b2436af03029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['doctor_id'], ['id'])

    with op.batch_alter_table('doctor_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_patient', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_messages', schema=None) as batch_op:
        batch_op.drop_column('is_from_patient')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
